# Stage 1: Build
FROM public.ecr.aws/lambda/nodejs:22 AS builder

WORKDIR /build

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.json ./
COPY scripts/ ./scripts/
COPY src/ ./src/

RUN npm install -g corepack@latest && corepack enable

RUN pnpm install --frozen-lockfile --aggregate-output

RUN pnpm run build

RUN pnpm prune --prod

# Stage 2: Production
FROM public.ecr.aws/lambda/nodejs:22

ENV NODE_ENV=production

WORKDIR ${LAMBDA_TASK_ROOT}

COPY package.json ./

COPY --from=builder /build/built/ ./built/
COPY --from=builder /build/node_modules/ ./node_modules/

COPY nsfw-model/ ./nsfw-model/

# systeminformationがCPUフラグとして空配列を返すが、nsfwjs, tfjsは正常に動作するのでチェック結果を無視する
ENV SKIP_CPUFLAGS_CHECK=1

CMD ["built/index.handler"]
